In [2]:
import pandas as pd
df = pd.read_csv('../notebooks/Myocardial infarction complications Database (1).csv')
df.head()

,ID,AGE,SEX,INF_ANAM,STENOK_AN,FK_STENOK,IBS_POST,IBS_NASL,GB,SIM_GIPERT,...,JELUD_TAH,FIBR_JELUD,A_V_BLOK,OTEK_LANC,RAZRIV,DRESSLER,ZSN,REC_IM,P_IM_STEN,LET_IS
0,1,77.0,1,2.0,1.0,1.0,2.0,NaN,3.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,2,55.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,3,52.0,1,0.0,0.0,0.0,2.0,NaN,2.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,4,68.0,0,0.0,0.0,0.0,2.0,NaN,2.0,0.0,...,0,0,0,0,0,0,1,0,0,0
4,5,60.0,1,0.0,0.0,0.0,2.0,NaN,3.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
lista_de_delete = ["ID", "IBS_NASL", "KFK_BLOOD", "JELUD_TAH", "FIBR_JELUD", "A_V_BLOK", "OTEK_LANC", "RAZRIV", "DRESSLER", "REC_IM", "P_IM_STEN", "LET_IS", "PREDS_TAH", "FIBR_PREDS"]
df = df.drop(lista_de_delete, axis=1)
df.head(1700)

,AGE,SEX,INF_ANAM,STENOK_AN,FK_STENOK,IBS_POST,GB,SIM_GIPERT,DLIT_AG,ZSN_A,...,NOT_NA_2_n,NOT_NA_3_n,LID_S_n,B_BLOK_S_n,ANT_CA_S_n,GEPAR_S_n,ASP_S_n,TIKL_S_n,TRENT_S_n,ZSN
0,77.0,1,2.0,1.0,1.0,2.0,3.0,0.0,7.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0
1,55.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0
2,52.0,1,0.0,0.0,0.0,2.0,2.0,0.0,2.0,0.0,...,2.0,2.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0
3,68.0,0,0.0,0.0,0.0,2.0,2.0,0.0,3.0,1.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1
4,60.0,1,0.0,0.0,0.0,2.0,3.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1695,77.0,0,0.0,4.0,2.0,1.0,2.0,0.0,7.0,0.0,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1696,70.0,0,0.0,6.0,2.0,1.0,2.0,0.0,7.0,0.0,...,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1697,55.0,1,3.0,6.0,2.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0
1698,79.0,0,2.0,2.0,2.0,1.0,2.0,0.0,7.0,NaN,...,NaN,NaN,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0
1699,63.0,1,2.0,NaN,NaN,NaN,2.0,0.0,NaN,4.0,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

CriaÃ§Ã£o de um dicionÃ¡rio apenas para saber qual o index de cada coluna.

In [4]:
columns_list = df.columns.tolist()

dicionario = {}
for coluna in columns_list:
    index = columns_list.index(coluna)
    dicionario[coluna] = index
print(dicionario)

{'AGE': 0, 'SEX': 1, 'INF_ANAM': 2, 'STENOK_AN': 3, 'FK_STENOK': 4, 'IBS_POST': 5, 'GB': 6, 'SIM_GIPERT': 7, 'DLIT_AG': 8, 'ZSN_A': 9, 'nr_11': 10, 'nr_01': 11, 'nr_02': 12, 'nr_03': 13, 'nr_04': 14, 'nr_07': 15, 'nr_08': 16, 'np_01': 17, 'np_04': 18, 'np_05': 19, 'np_07': 20, 'np_08': 21, 'np_09': 22, 'np_10': 23, 'endocr_01': 24, 'endocr_02': 25, 'endocr_03': 26, 'zab_leg_01': 27, 'zab_leg_02': 28, 'zab_leg_03': 29, 'zab_leg_04': 30, 'zab_leg_06': 31, 'S_AD_KBRIG': 32, 'D_AD_KBRIG': 33, 'S_AD_ORIT': 34, 'D_AD_ORIT': 35, 'O_L_POST': 36, 'K_SH_POST': 37, 'MP_TP_POST': 38, 'SVT_POST': 39, 'GT_POST': 40, 'FIB_G_POST': 41, 'ant_im': 42, 'lat_im': 43, 'inf_im': 44, 'post_im': 45, 'IM_PG_P': 46, 'ritm_ecg_p_01': 47, 'ritm_ecg_p_02': 48, 'ritm_ecg_p_04': 49, 'ritm_ecg_p_06': 50, 'ritm_ecg_p_07': 51, 'ritm_ecg_p_08': 52, 'n_r_ecg_p_01': 53, 'n_r_ecg_p_02': 54, 'n_r_ecg_p_03': 55, 'n_r_ecg_p_04': 56, 'n_r_ecg_p_05': 57, 'n_r_ecg_p_06': 58, 'n_r_ecg_p_08': 59, 'n_r_ecg_p_09': 60, 'n_r_ecg_p_10': 61, 'n_p_ecg_p_01': 62, 'n_p_ecg_p_03': 63, 'n_p_ecg_p_04': 64, 'n_p_ecg_p_05': 65, 'n_p_ecg_p_06': 66, 'n_p_ecg_p_07': 67, 'n_p_ecg_p_08': 68, 'n_p_ecg_p_09': 69, 'n_p_ecg_p_10': 70, 'n_p_ecg_p_11': 71, 'n_p_ecg_p_12': 72, 'fibr_ter_01': 73, 'fibr_ter_02': 74, 'fibr_ter_03': 75, 'fibr_ter_05': 76, 'fibr_ter_06': 77, 'fibr_ter_07': 78, 'fibr_ter_08': 79, 'GIPO_K': 80, 'K_BLOOD': 81, 'GIPER_NA': 82, 'NA_BLOOD': 83, 'ALT_BLOOD': 84, 'AST_BLOOD': 85, 'L_BLOOD': 86, 'ROE': 87, 'TIME_B_S': 88, 'R_AB_1_n': 89, 'R_AB_2_n': 90, 'R_AB_3_n': 91, 'NA_KB': 92, 'NOT_NA_KB': 93, 'LID_KB': 94, 'NITR_S': 95, 'NA_R_1_n': 96, 'NA_R_2_n': 97, 'NA_R_3_n': 98, 'NOT_NA_1_n': 99, 'NOT_NA_2_n': 100, 'NOT_NA_3_n': 101, 'LID_S_n': 102, 'B_BLOK_S_n': 103, 'ANT_CA_S_n': 104, 'GEPAR_S_n': 105, 'ASP_S_n': 106, 'TIKL_S_n': 107, 'TRENT_S_n': 108, 'ZSN': 109}

In [5]:

tirar_a_moda = df.columns

for coluna in tirar_a_moda:
    if coluna == "AGE":
        mediana = df[coluna].median()
        df[coluna].fillna(mediana, inplace=True)
    elif coluna == "SEX" or coluna == "S_AD_KBRIG" or coluna == "D_AD_KBRIG" or coluna == "GIPO_K" or coluna == "K_BLOOD" or coluna == "GIPER_Na" or coluna == "Na_BLOOD" or coluna == "ALT_BLOOD" or coluna == "AST_BLOOD" or coluna == "ROE" or coluna == "TIME_B_S" or coluna == "NA_KB" or coluna == "NOT_NA_KB" or coluna == "LID_KB" or coluna == "R_AB_3_n" or coluna == "NITR_S":
        continue
    elif coluna == "S_AD_ORIT" or coluna == "D_AD_ORIT":
        media = df[coluna].median()
        df[coluna].fillna(mediana, inplace=True)
    else:
        moda = df[coluna].mode().values[0]
        df[coluna].fillna(moda, inplace=True)
print("FIM DO LOOP\n")

FIM DO LOOP

In [7]:
df.head(1700)

,AGE,SEX,INF_ANAM,STENOK_AN,FK_STENOK,IBS_POST,GB,SIM_GIPERT,DLIT_AG,ZSN_A,...,NOT_NA_2_n,NOT_NA_3_n,LID_S_n,B_BLOK_S_n,ANT_CA_S_n,GEPAR_S_n,ASP_S_n,TIKL_S_n,TRENT_S_n,ZSN
0,77.0,1,2.0,1.0,1.0,2.0,3.0,0.0,7.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0
1,55.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0
2,52.0,1,0.0,0.0,0.0,2.0,2.0,0.0,2.0,0.0,...,2.0,2.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0
3,68.0,0,0.0,0.0,0.0,2.0,2.0,0.0,3.0,1.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1
4,60.0,1,0.0,0.0,0.0,2.0,3.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1695,77.0,0,0.0,4.0,2.0,1.0,2.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1696,70.0,0,0.0,6.0,2.0,1.0,2.0,0.0,7.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1697,55.0,1,3.0,6.0,2.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0
1698,79.0,0,2.0,2.0,2.0,1.0,2.0,0.0,7.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0
1699,63.0,1,2.0,0.0,2.0,2.0,2.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0